// Generated by gencpp from file ros_img_processor/camera_POI_msg.msg
// DO NOT EDIT!


#ifndef ROS_IMG_PROCESSOR_MESSAGE_CAMERA_POI_MSG_H
#define ROS_IMG_PROCESSOR_MESSAGE_CAMERA_POI_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>

namespace ros_img_processor
{
template <class ContainerAllocator>
struct camera_POI_msg_
{
  typedef camera_POI_msg_<ContainerAllocator> Type;

  camera_POI_msg_()
    : Header()
    , type()
    , pointleft()
    , pointright()  {
    }
  camera_POI_msg_(const ContainerAllocator& _alloc)
    : Header(_alloc)
    , type(_alloc)
    , pointleft(_alloc)
    , pointright(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _Header_type;
  _Header_type Header;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _type_type;
  _type_type type;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _pointleft_type;
  _pointleft_type pointleft;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _pointright_type;
  _pointright_type pointright;





  typedef boost::shared_ptr< ::ros_img_processor::camera_POI_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_img_processor::camera_POI_msg_<ContainerAllocator> const> ConstPtr;

}; // struct camera_POI_msg_

typedef ::ros_img_processor::camera_POI_msg_<std::allocator<void> > camera_POI_msg;

typedef boost::shared_ptr< ::ros_img_processor::camera_POI_msg > camera_POI_msgPtr;
typedef boost::shared_ptr< ::ros_img_processor::camera_POI_msg const> camera_POI_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_img_processor::camera_POI_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_img_processor::camera_POI_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_img_processor::camera_POI_msg_<ContainerAllocator1> & lhs, const ::ros_img_processor::camera_POI_msg_<ContainerAllocator2> & rhs)
{
  return lhs.Header == rhs.Header &&
    lhs.type == rhs.type &&
    lhs.pointleft == rhs.pointleft &&
    lhs.pointright == rhs.pointright;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_img_processor::camera_POI_msg_<ContainerAllocator1> & lhs, const ::ros_img_processor::camera_POI_msg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_img_processor

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ros_img_processor::camera_POI_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_img_processor::camera_POI_msg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_img_processor::camera_POI_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_img_processor::camera_POI_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_img_processor::camera_POI_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_img_processor::camera_POI_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_img_processor::camera_POI_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3889b5518a505b6dff84d0f699e8b734";
  }

  static const char* value(const ::ros_img_processor::camera_POI_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3889b5518a505b6dULL;
  static const uint64_t static_value2 = 0xff84d0f699e8b734ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_img_processor::camera_POI_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_img_processor/camera_POI_msg";
  }

  static const char* value(const ::ros_img_processor::camera_POI_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_img_processor::camera_POI_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header Header\n"
"string type\n"
"geometry_msgs/Point pointleft\n"
"geometry_msgs/Point pointright\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::ros_img_processor::camera_POI_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_img_processor::camera_POI_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Header);
      stream.next(m.type);
      stream.next(m.pointleft);
      stream.next(m.pointright);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct camera_POI_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_img_processor::camera_POI_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_img_processor::camera_POI_msg_<ContainerAllocator>& v)
  {
    s << indent << "Header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.Header);
    s << indent << "type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.type);
    s << indent << "pointleft: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.pointleft);
    s << indent << "pointright: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.pointright);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_IMG_PROCESSOR_MESSAGE_CAMERA_POI_MSG_H
