// Generated by gencpp from file turtlebot_2dnav/askNewFrontier.msg
// DO NOT EDIT!


#ifndef TURTLEBOT_2DNAV_MESSAGE_ASKNEWFRONTIER_H
#define TURTLEBOT_2DNAV_MESSAGE_ASKNEWFRONTIER_H

#include <ros/service_traits.h>


#include <turtlebot_2dnav/askNewFrontierRequest.h>
#include <turtlebot_2dnav/askNewFrontierResponse.h>


namespace turtlebot_2dnav
{

struct askNewFrontier
{

typedef askNewFrontierRequest Request;
typedef askNewFrontierResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct askNewFrontier
} // namespace turtlebot_2dnav


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::turtlebot_2dnav::askNewFrontier > {
  static const char* value()
  {
    return "1218c344901f1bfc2f1bcf338db224b8";
  }

  static const char* value(const ::turtlebot_2dnav::askNewFrontier&) { return value(); }
};

template<>
struct DataType< ::turtlebot_2dnav::askNewFrontier > {
  static const char* value()
  {
    return "turtlebot_2dnav/askNewFrontier";
  }

  static const char* value(const ::turtlebot_2dnav::askNewFrontier&) { return value(); }
};


// service_traits::MD5Sum< ::turtlebot_2dnav::askNewFrontierRequest> should match
// service_traits::MD5Sum< ::turtlebot_2dnav::askNewFrontier >
template<>
struct MD5Sum< ::turtlebot_2dnav::askNewFrontierRequest>
{
  static const char* value()
  {
    return MD5Sum< ::turtlebot_2dnav::askNewFrontier >::value();
  }
  static const char* value(const ::turtlebot_2dnav::askNewFrontierRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtlebot_2dnav::askNewFrontierRequest> should match
// service_traits::DataType< ::turtlebot_2dnav::askNewFrontier >
template<>
struct DataType< ::turtlebot_2dnav::askNewFrontierRequest>
{
  static const char* value()
  {
    return DataType< ::turtlebot_2dnav::askNewFrontier >::value();
  }
  static const char* value(const ::turtlebot_2dnav::askNewFrontierRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::turtlebot_2dnav::askNewFrontierResponse> should match
// service_traits::MD5Sum< ::turtlebot_2dnav::askNewFrontier >
template<>
struct MD5Sum< ::turtlebot_2dnav::askNewFrontierResponse>
{
  static const char* value()
  {
    return MD5Sum< ::turtlebot_2dnav::askNewFrontier >::value();
  }
  static const char* value(const ::turtlebot_2dnav::askNewFrontierResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtlebot_2dnav::askNewFrontierResponse> should match
// service_traits::DataType< ::turtlebot_2dnav::askNewFrontier >
template<>
struct DataType< ::turtlebot_2dnav::askNewFrontierResponse>
{
  static const char* value()
  {
    return DataType< ::turtlebot_2dnav::askNewFrontier >::value();
  }
  static const char* value(const ::turtlebot_2dnav::askNewFrontierResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TURTLEBOT_2DNAV_MESSAGE_ASKNEWFRONTIER_H
