// Generated by gencpp from file turtlebot_2dnav/askNewFrontierRequest.msg
// DO NOT EDIT!


#ifndef TURTLEBOT_2DNAV_MESSAGE_ASKNEWFRONTIERREQUEST_H
#define TURTLEBOT_2DNAV_MESSAGE_ASKNEWFRONTIERREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace turtlebot_2dnav
{
template <class ContainerAllocator>
struct askNewFrontierRequest_
{
  typedef askNewFrontierRequest_<ContainerAllocator> Type;

  askNewFrontierRequest_()
    : addBlacklist(false)
    , clearBlacklist(false)  {
    }
  askNewFrontierRequest_(const ContainerAllocator& _alloc)
    : addBlacklist(false)
    , clearBlacklist(false)  {
  (void)_alloc;
    }



   typedef uint8_t _addBlacklist_type;
  _addBlacklist_type addBlacklist;

   typedef uint8_t _clearBlacklist_type;
  _clearBlacklist_type clearBlacklist;





  typedef boost::shared_ptr< ::turtlebot_2dnav::askNewFrontierRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::turtlebot_2dnav::askNewFrontierRequest_<ContainerAllocator> const> ConstPtr;

}; // struct askNewFrontierRequest_

typedef ::turtlebot_2dnav::askNewFrontierRequest_<std::allocator<void> > askNewFrontierRequest;

typedef boost::shared_ptr< ::turtlebot_2dnav::askNewFrontierRequest > askNewFrontierRequestPtr;
typedef boost::shared_ptr< ::turtlebot_2dnav::askNewFrontierRequest const> askNewFrontierRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::turtlebot_2dnav::askNewFrontierRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::turtlebot_2dnav::askNewFrontierRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::turtlebot_2dnav::askNewFrontierRequest_<ContainerAllocator1> & lhs, const ::turtlebot_2dnav::askNewFrontierRequest_<ContainerAllocator2> & rhs)
{
  return lhs.addBlacklist == rhs.addBlacklist &&
    lhs.clearBlacklist == rhs.clearBlacklist;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::turtlebot_2dnav::askNewFrontierRequest_<ContainerAllocator1> & lhs, const ::turtlebot_2dnav::askNewFrontierRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace turtlebot_2dnav

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::turtlebot_2dnav::askNewFrontierRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtlebot_2dnav::askNewFrontierRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtlebot_2dnav::askNewFrontierRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtlebot_2dnav::askNewFrontierRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtlebot_2dnav::askNewFrontierRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtlebot_2dnav::askNewFrontierRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::turtlebot_2dnav::askNewFrontierRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f91fbc6af54a796311a6569836b84444";
  }

  static const char* value(const ::turtlebot_2dnav::askNewFrontierRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf91fbc6af54a7963ULL;
  static const uint64_t static_value2 = 0x11a6569836b84444ULL;
};

template<class ContainerAllocator>
struct DataType< ::turtlebot_2dnav::askNewFrontierRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "turtlebot_2dnav/askNewFrontierRequest";
  }

  static const char* value(const ::turtlebot_2dnav::askNewFrontierRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::turtlebot_2dnav::askNewFrontierRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool addBlacklist\n"
"bool clearBlacklist\n"
;
  }

  static const char* value(const ::turtlebot_2dnav::askNewFrontierRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::turtlebot_2dnav::askNewFrontierRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.addBlacklist);
      stream.next(m.clearBlacklist);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct askNewFrontierRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::turtlebot_2dnav::askNewFrontierRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::turtlebot_2dnav::askNewFrontierRequest_<ContainerAllocator>& v)
  {
    s << indent << "addBlacklist: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.addBlacklist);
    s << indent << "clearBlacklist: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.clearBlacklist);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TURTLEBOT_2DNAV_MESSAGE_ASKNEWFRONTIERREQUEST_H
