// Generated by gencpp from file turtlebot_2dnav/clearCostmap.msg
// DO NOT EDIT!


#ifndef TURTLEBOT_2DNAV_MESSAGE_CLEARCOSTMAP_H
#define TURTLEBOT_2DNAV_MESSAGE_CLEARCOSTMAP_H

#include <ros/service_traits.h>


#include <turtlebot_2dnav/clearCostmapRequest.h>
#include <turtlebot_2dnav/clearCostmapResponse.h>


namespace turtlebot_2dnav
{

struct clearCostmap
{

typedef clearCostmapRequest Request;
typedef clearCostmapResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct clearCostmap
} // namespace turtlebot_2dnav


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::turtlebot_2dnav::clearCostmap > {
  static const char* value()
  {
    return "6f1cadb125ab62799a65523a8282332f";
  }

  static const char* value(const ::turtlebot_2dnav::clearCostmap&) { return value(); }
};

template<>
struct DataType< ::turtlebot_2dnav::clearCostmap > {
  static const char* value()
  {
    return "turtlebot_2dnav/clearCostmap";
  }

  static const char* value(const ::turtlebot_2dnav::clearCostmap&) { return value(); }
};


// service_traits::MD5Sum< ::turtlebot_2dnav::clearCostmapRequest> should match
// service_traits::MD5Sum< ::turtlebot_2dnav::clearCostmap >
template<>
struct MD5Sum< ::turtlebot_2dnav::clearCostmapRequest>
{
  static const char* value()
  {
    return MD5Sum< ::turtlebot_2dnav::clearCostmap >::value();
  }
  static const char* value(const ::turtlebot_2dnav::clearCostmapRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtlebot_2dnav::clearCostmapRequest> should match
// service_traits::DataType< ::turtlebot_2dnav::clearCostmap >
template<>
struct DataType< ::turtlebot_2dnav::clearCostmapRequest>
{
  static const char* value()
  {
    return DataType< ::turtlebot_2dnav::clearCostmap >::value();
  }
  static const char* value(const ::turtlebot_2dnav::clearCostmapRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::turtlebot_2dnav::clearCostmapResponse> should match
// service_traits::MD5Sum< ::turtlebot_2dnav::clearCostmap >
template<>
struct MD5Sum< ::turtlebot_2dnav::clearCostmapResponse>
{
  static const char* value()
  {
    return MD5Sum< ::turtlebot_2dnav::clearCostmap >::value();
  }
  static const char* value(const ::turtlebot_2dnav::clearCostmapResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtlebot_2dnav::clearCostmapResponse> should match
// service_traits::DataType< ::turtlebot_2dnav::clearCostmap >
template<>
struct DataType< ::turtlebot_2dnav::clearCostmapResponse>
{
  static const char* value()
  {
    return DataType< ::turtlebot_2dnav::clearCostmap >::value();
  }
  static const char* value(const ::turtlebot_2dnav::clearCostmapResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TURTLEBOT_2DNAV_MESSAGE_CLEARCOSTMAP_H
