// Generated by gencpp from file turtlebot_2dnav/fakeLaser.msg
// DO NOT EDIT!


#ifndef TURTLEBOT_2DNAV_MESSAGE_FAKELASER_H
#define TURTLEBOT_2DNAV_MESSAGE_FAKELASER_H

#include <ros/service_traits.h>


#include <turtlebot_2dnav/fakeLaserRequest.h>
#include <turtlebot_2dnav/fakeLaserResponse.h>


namespace turtlebot_2dnav
{

struct fakeLaser
{

typedef fakeLaserRequest Request;
typedef fakeLaserResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct fakeLaser
} // namespace turtlebot_2dnav


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::turtlebot_2dnav::fakeLaser > {
  static const char* value()
  {
    return "313460372e25eee11ab9126733a5d19c";
  }

  static const char* value(const ::turtlebot_2dnav::fakeLaser&) { return value(); }
};

template<>
struct DataType< ::turtlebot_2dnav::fakeLaser > {
  static const char* value()
  {
    return "turtlebot_2dnav/fakeLaser";
  }

  static const char* value(const ::turtlebot_2dnav::fakeLaser&) { return value(); }
};


// service_traits::MD5Sum< ::turtlebot_2dnav::fakeLaserRequest> should match
// service_traits::MD5Sum< ::turtlebot_2dnav::fakeLaser >
template<>
struct MD5Sum< ::turtlebot_2dnav::fakeLaserRequest>
{
  static const char* value()
  {
    return MD5Sum< ::turtlebot_2dnav::fakeLaser >::value();
  }
  static const char* value(const ::turtlebot_2dnav::fakeLaserRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtlebot_2dnav::fakeLaserRequest> should match
// service_traits::DataType< ::turtlebot_2dnav::fakeLaser >
template<>
struct DataType< ::turtlebot_2dnav::fakeLaserRequest>
{
  static const char* value()
  {
    return DataType< ::turtlebot_2dnav::fakeLaser >::value();
  }
  static const char* value(const ::turtlebot_2dnav::fakeLaserRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::turtlebot_2dnav::fakeLaserResponse> should match
// service_traits::MD5Sum< ::turtlebot_2dnav::fakeLaser >
template<>
struct MD5Sum< ::turtlebot_2dnav::fakeLaserResponse>
{
  static const char* value()
  {
    return MD5Sum< ::turtlebot_2dnav::fakeLaser >::value();
  }
  static const char* value(const ::turtlebot_2dnav::fakeLaserResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtlebot_2dnav::fakeLaserResponse> should match
// service_traits::DataType< ::turtlebot_2dnav::fakeLaser >
template<>
struct DataType< ::turtlebot_2dnav::fakeLaserResponse>
{
  static const char* value()
  {
    return DataType< ::turtlebot_2dnav::fakeLaser >::value();
  }
  static const char* value(const ::turtlebot_2dnav::fakeLaserResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TURTLEBOT_2DNAV_MESSAGE_FAKELASER_H
