// Generated by gencpp from file turtlebot_2dnav/fakeLaserResponse.msg
// DO NOT EDIT!


#ifndef TURTLEBOT_2DNAV_MESSAGE_FAKELASERRESPONSE_H
#define TURTLEBOT_2DNAV_MESSAGE_FAKELASERRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace turtlebot_2dnav
{
template <class ContainerAllocator>
struct fakeLaserResponse_
{
  typedef fakeLaserResponse_<ContainerAllocator> Type;

  fakeLaserResponse_()
    : received(false)  {
    }
  fakeLaserResponse_(const ContainerAllocator& _alloc)
    : received(false)  {
  (void)_alloc;
    }



   typedef uint8_t _received_type;
  _received_type received;





  typedef boost::shared_ptr< ::turtlebot_2dnav::fakeLaserResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::turtlebot_2dnav::fakeLaserResponse_<ContainerAllocator> const> ConstPtr;

}; // struct fakeLaserResponse_

typedef ::turtlebot_2dnav::fakeLaserResponse_<std::allocator<void> > fakeLaserResponse;

typedef boost::shared_ptr< ::turtlebot_2dnav::fakeLaserResponse > fakeLaserResponsePtr;
typedef boost::shared_ptr< ::turtlebot_2dnav::fakeLaserResponse const> fakeLaserResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::turtlebot_2dnav::fakeLaserResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::turtlebot_2dnav::fakeLaserResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::turtlebot_2dnav::fakeLaserResponse_<ContainerAllocator1> & lhs, const ::turtlebot_2dnav::fakeLaserResponse_<ContainerAllocator2> & rhs)
{
  return lhs.received == rhs.received;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::turtlebot_2dnav::fakeLaserResponse_<ContainerAllocator1> & lhs, const ::turtlebot_2dnav::fakeLaserResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace turtlebot_2dnav

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::turtlebot_2dnav::fakeLaserResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtlebot_2dnav::fakeLaserResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtlebot_2dnav::fakeLaserResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtlebot_2dnav::fakeLaserResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtlebot_2dnav::fakeLaserResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtlebot_2dnav::fakeLaserResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::turtlebot_2dnav::fakeLaserResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dd4152e077925db952c78baadb1e48b7";
  }

  static const char* value(const ::turtlebot_2dnav::fakeLaserResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdd4152e077925db9ULL;
  static const uint64_t static_value2 = 0x52c78baadb1e48b7ULL;
};

template<class ContainerAllocator>
struct DataType< ::turtlebot_2dnav::fakeLaserResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "turtlebot_2dnav/fakeLaserResponse";
  }

  static const char* value(const ::turtlebot_2dnav::fakeLaserResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::turtlebot_2dnav::fakeLaserResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool received\n"
"\n"
;
  }

  static const char* value(const ::turtlebot_2dnav::fakeLaserResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::turtlebot_2dnav::fakeLaserResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.received);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct fakeLaserResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::turtlebot_2dnav::fakeLaserResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::turtlebot_2dnav::fakeLaserResponse_<ContainerAllocator>& v)
  {
    s << indent << "received: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.received);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TURTLEBOT_2DNAV_MESSAGE_FAKELASERRESPONSE_H
