// Generated by gencpp from file turtlebot_2dnav/frontier.msg
// DO NOT EDIT!


#ifndef TURTLEBOT_2DNAV_MESSAGE_FRONTIER_H
#define TURTLEBOT_2DNAV_MESSAGE_FRONTIER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseStamped.h>

namespace turtlebot_2dnav
{
template <class ContainerAllocator>
struct frontier_
{
  typedef frontier_<ContainerAllocator> Type;

  frontier_()
    : goal()
    , frontiers_count(0)  {
    }
  frontier_(const ContainerAllocator& _alloc)
    : goal(_alloc)
    , frontiers_count(0)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _goal_type;
  _goal_type goal;

   typedef uint8_t _frontiers_count_type;
  _frontiers_count_type frontiers_count;





  typedef boost::shared_ptr< ::turtlebot_2dnav::frontier_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::turtlebot_2dnav::frontier_<ContainerAllocator> const> ConstPtr;

}; // struct frontier_

typedef ::turtlebot_2dnav::frontier_<std::allocator<void> > frontier;

typedef boost::shared_ptr< ::turtlebot_2dnav::frontier > frontierPtr;
typedef boost::shared_ptr< ::turtlebot_2dnav::frontier const> frontierConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::turtlebot_2dnav::frontier_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::turtlebot_2dnav::frontier_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::turtlebot_2dnav::frontier_<ContainerAllocator1> & lhs, const ::turtlebot_2dnav::frontier_<ContainerAllocator2> & rhs)
{
  return lhs.goal == rhs.goal &&
    lhs.frontiers_count == rhs.frontiers_count;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::turtlebot_2dnav::frontier_<ContainerAllocator1> & lhs, const ::turtlebot_2dnav::frontier_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace turtlebot_2dnav

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::turtlebot_2dnav::frontier_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtlebot_2dnav::frontier_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtlebot_2dnav::frontier_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtlebot_2dnav::frontier_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtlebot_2dnav::frontier_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtlebot_2dnav::frontier_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::turtlebot_2dnav::frontier_<ContainerAllocator> >
{
  static const char* value()
  {
    return "72fa4e2f921957ecbe666961f3773de7";
  }

  static const char* value(const ::turtlebot_2dnav::frontier_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x72fa4e2f921957ecULL;
  static const uint64_t static_value2 = 0xbe666961f3773de7ULL;
};

template<class ContainerAllocator>
struct DataType< ::turtlebot_2dnav::frontier_<ContainerAllocator> >
{
  static const char* value()
  {
    return "turtlebot_2dnav/frontier";
  }

  static const char* value(const ::turtlebot_2dnav::frontier_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::turtlebot_2dnav::frontier_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/PoseStamped goal\n"
"uint8 frontiers_count\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::turtlebot_2dnav::frontier_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::turtlebot_2dnav::frontier_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.goal);
      stream.next(m.frontiers_count);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct frontier_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::turtlebot_2dnav::frontier_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::turtlebot_2dnav::frontier_<ContainerAllocator>& v)
  {
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
    s << indent << "frontiers_count: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.frontiers_count);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TURTLEBOT_2DNAV_MESSAGE_FRONTIER_H
