// Generated by gencpp from file turtlebot_2dnav/match_bound.msg
// DO NOT EDIT!


#ifndef TURTLEBOT_2DNAV_MESSAGE_MATCH_BOUND_H
#define TURTLEBOT_2DNAV_MESSAGE_MATCH_BOUND_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>

namespace turtlebot_2dnav
{
template <class ContainerAllocator>
struct match_bound_
{
  typedef match_bound_<ContainerAllocator> Type;

  match_bound_()
    : pointright()
    , pointleft()
    , pointcenter()
    , matched(false)
    , index(0)
    , color(0)  {
    }
  match_bound_(const ContainerAllocator& _alloc)
    : pointright(_alloc)
    , pointleft(_alloc)
    , pointcenter(_alloc)
    , matched(false)
    , index(0)
    , color(0)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _pointright_type;
  _pointright_type pointright;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _pointleft_type;
  _pointleft_type pointleft;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _pointcenter_type;
  _pointcenter_type pointcenter;

   typedef uint8_t _matched_type;
  _matched_type matched;

   typedef int32_t _index_type;
  _index_type index;

   typedef int32_t _color_type;
  _color_type color;





  typedef boost::shared_ptr< ::turtlebot_2dnav::match_bound_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::turtlebot_2dnav::match_bound_<ContainerAllocator> const> ConstPtr;

}; // struct match_bound_

typedef ::turtlebot_2dnav::match_bound_<std::allocator<void> > match_bound;

typedef boost::shared_ptr< ::turtlebot_2dnav::match_bound > match_boundPtr;
typedef boost::shared_ptr< ::turtlebot_2dnav::match_bound const> match_boundConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::turtlebot_2dnav::match_bound_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::turtlebot_2dnav::match_bound_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::turtlebot_2dnav::match_bound_<ContainerAllocator1> & lhs, const ::turtlebot_2dnav::match_bound_<ContainerAllocator2> & rhs)
{
  return lhs.pointright == rhs.pointright &&
    lhs.pointleft == rhs.pointleft &&
    lhs.pointcenter == rhs.pointcenter &&
    lhs.matched == rhs.matched &&
    lhs.index == rhs.index &&
    lhs.color == rhs.color;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::turtlebot_2dnav::match_bound_<ContainerAllocator1> & lhs, const ::turtlebot_2dnav::match_bound_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace turtlebot_2dnav

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::turtlebot_2dnav::match_bound_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtlebot_2dnav::match_bound_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtlebot_2dnav::match_bound_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtlebot_2dnav::match_bound_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtlebot_2dnav::match_bound_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtlebot_2dnav::match_bound_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::turtlebot_2dnav::match_bound_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c25fb2723cbd0da8861846f432114884";
  }

  static const char* value(const ::turtlebot_2dnav::match_bound_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc25fb2723cbd0da8ULL;
  static const uint64_t static_value2 = 0x861846f432114884ULL;
};

template<class ContainerAllocator>
struct DataType< ::turtlebot_2dnav::match_bound_<ContainerAllocator> >
{
  static const char* value()
  {
    return "turtlebot_2dnav/match_bound";
  }

  static const char* value(const ::turtlebot_2dnav::match_bound_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::turtlebot_2dnav::match_bound_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Point pointright\n"
"geometry_msgs/Point pointleft\n"
"geometry_msgs/Point pointcenter\n"
"bool matched\n"
"int32 index\n"
"int32 color\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::turtlebot_2dnav::match_bound_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::turtlebot_2dnav::match_bound_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pointright);
      stream.next(m.pointleft);
      stream.next(m.pointcenter);
      stream.next(m.matched);
      stream.next(m.index);
      stream.next(m.color);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct match_bound_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::turtlebot_2dnav::match_bound_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::turtlebot_2dnav::match_bound_<ContainerAllocator>& v)
  {
    s << indent << "pointright: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.pointright);
    s << indent << "pointleft: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.pointleft);
    s << indent << "pointcenter: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.pointcenter);
    s << indent << "matched: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.matched);
    s << indent << "index: ";
    Printer<int32_t>::stream(s, indent + "  ", v.index);
    s << indent << "color: ";
    Printer<int32_t>::stream(s, indent + "  ", v.color);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TURTLEBOT_2DNAV_MESSAGE_MATCH_BOUND_H
