// Generated by gencpp from file turtlebot_2dnav/recalculateBound.msg
// DO NOT EDIT!


#ifndef TURTLEBOT_2DNAV_MESSAGE_RECALCULATEBOUND_H
#define TURTLEBOT_2DNAV_MESSAGE_RECALCULATEBOUND_H

#include <ros/service_traits.h>


#include <turtlebot_2dnav/recalculateBoundRequest.h>
#include <turtlebot_2dnav/recalculateBoundResponse.h>


namespace turtlebot_2dnav
{

struct recalculateBound
{

typedef recalculateBoundRequest Request;
typedef recalculateBoundResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct recalculateBound
} // namespace turtlebot_2dnav


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::turtlebot_2dnav::recalculateBound > {
  static const char* value()
  {
    return "ccb08b87036c8a7862161f690fdb0a11";
  }

  static const char* value(const ::turtlebot_2dnav::recalculateBound&) { return value(); }
};

template<>
struct DataType< ::turtlebot_2dnav::recalculateBound > {
  static const char* value()
  {
    return "turtlebot_2dnav/recalculateBound";
  }

  static const char* value(const ::turtlebot_2dnav::recalculateBound&) { return value(); }
};


// service_traits::MD5Sum< ::turtlebot_2dnav::recalculateBoundRequest> should match
// service_traits::MD5Sum< ::turtlebot_2dnav::recalculateBound >
template<>
struct MD5Sum< ::turtlebot_2dnav::recalculateBoundRequest>
{
  static const char* value()
  {
    return MD5Sum< ::turtlebot_2dnav::recalculateBound >::value();
  }
  static const char* value(const ::turtlebot_2dnav::recalculateBoundRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtlebot_2dnav::recalculateBoundRequest> should match
// service_traits::DataType< ::turtlebot_2dnav::recalculateBound >
template<>
struct DataType< ::turtlebot_2dnav::recalculateBoundRequest>
{
  static const char* value()
  {
    return DataType< ::turtlebot_2dnav::recalculateBound >::value();
  }
  static const char* value(const ::turtlebot_2dnav::recalculateBoundRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::turtlebot_2dnav::recalculateBoundResponse> should match
// service_traits::MD5Sum< ::turtlebot_2dnav::recalculateBound >
template<>
struct MD5Sum< ::turtlebot_2dnav::recalculateBoundResponse>
{
  static const char* value()
  {
    return MD5Sum< ::turtlebot_2dnav::recalculateBound >::value();
  }
  static const char* value(const ::turtlebot_2dnav::recalculateBoundResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtlebot_2dnav::recalculateBoundResponse> should match
// service_traits::DataType< ::turtlebot_2dnav::recalculateBound >
template<>
struct DataType< ::turtlebot_2dnav::recalculateBoundResponse>
{
  static const char* value()
  {
    return DataType< ::turtlebot_2dnav::recalculateBound >::value();
  }
  static const char* value(const ::turtlebot_2dnav::recalculateBoundResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TURTLEBOT_2DNAV_MESSAGE_RECALCULATEBOUND_H
