// Generated by gencpp from file turtlebot_2dnav/recalculateBoundRequest.msg
// DO NOT EDIT!


#ifndef TURTLEBOT_2DNAV_MESSAGE_RECALCULATEBOUNDREQUEST_H
#define TURTLEBOT_2DNAV_MESSAGE_RECALCULATEBOUNDREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace turtlebot_2dnav
{
template <class ContainerAllocator>
struct recalculateBoundRequest_
{
  typedef recalculateBoundRequest_<ContainerAllocator> Type;

  recalculateBoundRequest_()
    : recalculate(false)  {
    }
  recalculateBoundRequest_(const ContainerAllocator& _alloc)
    : recalculate(false)  {
  (void)_alloc;
    }



   typedef uint8_t _recalculate_type;
  _recalculate_type recalculate;





  typedef boost::shared_ptr< ::turtlebot_2dnav::recalculateBoundRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::turtlebot_2dnav::recalculateBoundRequest_<ContainerAllocator> const> ConstPtr;

}; // struct recalculateBoundRequest_

typedef ::turtlebot_2dnav::recalculateBoundRequest_<std::allocator<void> > recalculateBoundRequest;

typedef boost::shared_ptr< ::turtlebot_2dnav::recalculateBoundRequest > recalculateBoundRequestPtr;
typedef boost::shared_ptr< ::turtlebot_2dnav::recalculateBoundRequest const> recalculateBoundRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::turtlebot_2dnav::recalculateBoundRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::turtlebot_2dnav::recalculateBoundRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::turtlebot_2dnav::recalculateBoundRequest_<ContainerAllocator1> & lhs, const ::turtlebot_2dnav::recalculateBoundRequest_<ContainerAllocator2> & rhs)
{
  return lhs.recalculate == rhs.recalculate;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::turtlebot_2dnav::recalculateBoundRequest_<ContainerAllocator1> & lhs, const ::turtlebot_2dnav::recalculateBoundRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace turtlebot_2dnav

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::turtlebot_2dnav::recalculateBoundRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtlebot_2dnav::recalculateBoundRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtlebot_2dnav::recalculateBoundRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtlebot_2dnav::recalculateBoundRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtlebot_2dnav::recalculateBoundRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtlebot_2dnav::recalculateBoundRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::turtlebot_2dnav::recalculateBoundRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "713c5ce4862e541c2c00a5b48ff7df97";
  }

  static const char* value(const ::turtlebot_2dnav::recalculateBoundRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x713c5ce4862e541cULL;
  static const uint64_t static_value2 = 0x2c00a5b48ff7df97ULL;
};

template<class ContainerAllocator>
struct DataType< ::turtlebot_2dnav::recalculateBoundRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "turtlebot_2dnav/recalculateBoundRequest";
  }

  static const char* value(const ::turtlebot_2dnav::recalculateBoundRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::turtlebot_2dnav::recalculateBoundRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool recalculate\n"
;
  }

  static const char* value(const ::turtlebot_2dnav::recalculateBoundRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::turtlebot_2dnav::recalculateBoundRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.recalculate);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct recalculateBoundRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::turtlebot_2dnav::recalculateBoundRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::turtlebot_2dnav::recalculateBoundRequest_<ContainerAllocator>& v)
  {
    s << indent << "recalculate: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.recalculate);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TURTLEBOT_2DNAV_MESSAGE_RECALCULATEBOUNDREQUEST_H
