// Generated by gencpp from file turtlebot_2dnav/restrictCostmapResponse.msg
// DO NOT EDIT!


#ifndef TURTLEBOT_2DNAV_MESSAGE_RESTRICTCOSTMAPRESPONSE_H
#define TURTLEBOT_2DNAV_MESSAGE_RESTRICTCOSTMAPRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace turtlebot_2dnav
{
template <class ContainerAllocator>
struct restrictCostmapResponse_
{
  typedef restrictCostmapResponse_<ContainerAllocator> Type;

  restrictCostmapResponse_()
    : received(false)
    , NewCenter()  {
    }
  restrictCostmapResponse_(const ContainerAllocator& _alloc)
    : received(false)
    , NewCenter(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _received_type;
  _received_type received;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _NewCenter_type;
  _NewCenter_type NewCenter;





  typedef boost::shared_ptr< ::turtlebot_2dnav::restrictCostmapResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::turtlebot_2dnav::restrictCostmapResponse_<ContainerAllocator> const> ConstPtr;

}; // struct restrictCostmapResponse_

typedef ::turtlebot_2dnav::restrictCostmapResponse_<std::allocator<void> > restrictCostmapResponse;

typedef boost::shared_ptr< ::turtlebot_2dnav::restrictCostmapResponse > restrictCostmapResponsePtr;
typedef boost::shared_ptr< ::turtlebot_2dnav::restrictCostmapResponse const> restrictCostmapResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::turtlebot_2dnav::restrictCostmapResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::turtlebot_2dnav::restrictCostmapResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::turtlebot_2dnav::restrictCostmapResponse_<ContainerAllocator1> & lhs, const ::turtlebot_2dnav::restrictCostmapResponse_<ContainerAllocator2> & rhs)
{
  return lhs.received == rhs.received &&
    lhs.NewCenter == rhs.NewCenter;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::turtlebot_2dnav::restrictCostmapResponse_<ContainerAllocator1> & lhs, const ::turtlebot_2dnav::restrictCostmapResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace turtlebot_2dnav

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::turtlebot_2dnav::restrictCostmapResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtlebot_2dnav::restrictCostmapResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtlebot_2dnav::restrictCostmapResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtlebot_2dnav::restrictCostmapResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtlebot_2dnav::restrictCostmapResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtlebot_2dnav::restrictCostmapResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::turtlebot_2dnav::restrictCostmapResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2123167eab87b647a50a6c172571b7b6";
  }

  static const char* value(const ::turtlebot_2dnav::restrictCostmapResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2123167eab87b647ULL;
  static const uint64_t static_value2 = 0xa50a6c172571b7b6ULL;
};

template<class ContainerAllocator>
struct DataType< ::turtlebot_2dnav::restrictCostmapResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "turtlebot_2dnav/restrictCostmapResponse";
  }

  static const char* value(const ::turtlebot_2dnav::restrictCostmapResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::turtlebot_2dnav::restrictCostmapResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool received\n"
"geometry_msgs/Point NewCenter\n"
"\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::turtlebot_2dnav::restrictCostmapResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::turtlebot_2dnav::restrictCostmapResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.received);
      stream.next(m.NewCenter);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct restrictCostmapResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::turtlebot_2dnav::restrictCostmapResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::turtlebot_2dnav::restrictCostmapResponse_<ContainerAllocator>& v)
  {
    s << indent << "received: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.received);
    s << indent << "NewCenter: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.NewCenter);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TURTLEBOT_2DNAV_MESSAGE_RESTRICTCOSTMAPRESPONSE_H
