// Generated by gencpp from file turtlebot_2dnav/restrictCostmap.msg
// DO NOT EDIT!


#ifndef TURTLEBOT_2DNAV_MESSAGE_RESTRICTCOSTMAP_H
#define TURTLEBOT_2DNAV_MESSAGE_RESTRICTCOSTMAP_H

#include <ros/service_traits.h>


#include <turtlebot_2dnav/restrictCostmapRequest.h>
#include <turtlebot_2dnav/restrictCostmapResponse.h>


namespace turtlebot_2dnav
{

struct restrictCostmap
{

typedef restrictCostmapRequest Request;
typedef restrictCostmapResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct restrictCostmap
} // namespace turtlebot_2dnav


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::turtlebot_2dnav::restrictCostmap > {
  static const char* value()
  {
    return "ca045509d540aafaf4518df5620d8993";
  }

  static const char* value(const ::turtlebot_2dnav::restrictCostmap&) { return value(); }
};

template<>
struct DataType< ::turtlebot_2dnav::restrictCostmap > {
  static const char* value()
  {
    return "turtlebot_2dnav/restrictCostmap";
  }

  static const char* value(const ::turtlebot_2dnav::restrictCostmap&) { return value(); }
};


// service_traits::MD5Sum< ::turtlebot_2dnav::restrictCostmapRequest> should match
// service_traits::MD5Sum< ::turtlebot_2dnav::restrictCostmap >
template<>
struct MD5Sum< ::turtlebot_2dnav::restrictCostmapRequest>
{
  static const char* value()
  {
    return MD5Sum< ::turtlebot_2dnav::restrictCostmap >::value();
  }
  static const char* value(const ::turtlebot_2dnav::restrictCostmapRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtlebot_2dnav::restrictCostmapRequest> should match
// service_traits::DataType< ::turtlebot_2dnav::restrictCostmap >
template<>
struct DataType< ::turtlebot_2dnav::restrictCostmapRequest>
{
  static const char* value()
  {
    return DataType< ::turtlebot_2dnav::restrictCostmap >::value();
  }
  static const char* value(const ::turtlebot_2dnav::restrictCostmapRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::turtlebot_2dnav::restrictCostmapResponse> should match
// service_traits::MD5Sum< ::turtlebot_2dnav::restrictCostmap >
template<>
struct MD5Sum< ::turtlebot_2dnav::restrictCostmapResponse>
{
  static const char* value()
  {
    return MD5Sum< ::turtlebot_2dnav::restrictCostmap >::value();
  }
  static const char* value(const ::turtlebot_2dnav::restrictCostmapResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtlebot_2dnav::restrictCostmapResponse> should match
// service_traits::DataType< ::turtlebot_2dnav::restrictCostmap >
template<>
struct DataType< ::turtlebot_2dnav::restrictCostmapResponse>
{
  static const char* value()
  {
    return DataType< ::turtlebot_2dnav::restrictCostmap >::value();
  }
  static const char* value(const ::turtlebot_2dnav::restrictCostmapResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TURTLEBOT_2DNAV_MESSAGE_RESTRICTCOSTMAP_H
