// Generated by gencpp from file turtlebot_2dnav/returnCost.msg
// DO NOT EDIT!


#ifndef TURTLEBOT_2DNAV_MESSAGE_RETURNCOST_H
#define TURTLEBOT_2DNAV_MESSAGE_RETURNCOST_H

#include <ros/service_traits.h>


#include <turtlebot_2dnav/returnCostRequest.h>
#include <turtlebot_2dnav/returnCostResponse.h>


namespace turtlebot_2dnav
{

struct returnCost
{

typedef returnCostRequest Request;
typedef returnCostResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct returnCost
} // namespace turtlebot_2dnav


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::turtlebot_2dnav::returnCost > {
  static const char* value()
  {
    return "f0ab08f6ab3861462bec12fbd2aae873";
  }

  static const char* value(const ::turtlebot_2dnav::returnCost&) { return value(); }
};

template<>
struct DataType< ::turtlebot_2dnav::returnCost > {
  static const char* value()
  {
    return "turtlebot_2dnav/returnCost";
  }

  static const char* value(const ::turtlebot_2dnav::returnCost&) { return value(); }
};


// service_traits::MD5Sum< ::turtlebot_2dnav::returnCostRequest> should match
// service_traits::MD5Sum< ::turtlebot_2dnav::returnCost >
template<>
struct MD5Sum< ::turtlebot_2dnav::returnCostRequest>
{
  static const char* value()
  {
    return MD5Sum< ::turtlebot_2dnav::returnCost >::value();
  }
  static const char* value(const ::turtlebot_2dnav::returnCostRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtlebot_2dnav::returnCostRequest> should match
// service_traits::DataType< ::turtlebot_2dnav::returnCost >
template<>
struct DataType< ::turtlebot_2dnav::returnCostRequest>
{
  static const char* value()
  {
    return DataType< ::turtlebot_2dnav::returnCost >::value();
  }
  static const char* value(const ::turtlebot_2dnav::returnCostRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::turtlebot_2dnav::returnCostResponse> should match
// service_traits::MD5Sum< ::turtlebot_2dnav::returnCost >
template<>
struct MD5Sum< ::turtlebot_2dnav::returnCostResponse>
{
  static const char* value()
  {
    return MD5Sum< ::turtlebot_2dnav::returnCost >::value();
  }
  static const char* value(const ::turtlebot_2dnav::returnCostResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtlebot_2dnav::returnCostResponse> should match
// service_traits::DataType< ::turtlebot_2dnav::returnCost >
template<>
struct DataType< ::turtlebot_2dnav::returnCostResponse>
{
  static const char* value()
  {
    return DataType< ::turtlebot_2dnav::returnCost >::value();
  }
  static const char* value(const ::turtlebot_2dnav::returnCostResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TURTLEBOT_2DNAV_MESSAGE_RETURNCOST_H
