// Generated by gencpp from file turtlebot_2dnav/returnCostResponse.msg
// DO NOT EDIT!


#ifndef TURTLEBOT_2DNAV_MESSAGE_RETURNCOSTRESPONSE_H
#define TURTLEBOT_2DNAV_MESSAGE_RETURNCOSTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace turtlebot_2dnav
{
template <class ContainerAllocator>
struct returnCostResponse_
{
  typedef returnCostResponse_<ContainerAllocator> Type;

  returnCostResponse_()
    : cost(0)  {
    }
  returnCostResponse_(const ContainerAllocator& _alloc)
    : cost(0)  {
  (void)_alloc;
    }



   typedef int64_t _cost_type;
  _cost_type cost;





  typedef boost::shared_ptr< ::turtlebot_2dnav::returnCostResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::turtlebot_2dnav::returnCostResponse_<ContainerAllocator> const> ConstPtr;

}; // struct returnCostResponse_

typedef ::turtlebot_2dnav::returnCostResponse_<std::allocator<void> > returnCostResponse;

typedef boost::shared_ptr< ::turtlebot_2dnav::returnCostResponse > returnCostResponsePtr;
typedef boost::shared_ptr< ::turtlebot_2dnav::returnCostResponse const> returnCostResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::turtlebot_2dnav::returnCostResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::turtlebot_2dnav::returnCostResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::turtlebot_2dnav::returnCostResponse_<ContainerAllocator1> & lhs, const ::turtlebot_2dnav::returnCostResponse_<ContainerAllocator2> & rhs)
{
  return lhs.cost == rhs.cost;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::turtlebot_2dnav::returnCostResponse_<ContainerAllocator1> & lhs, const ::turtlebot_2dnav::returnCostResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace turtlebot_2dnav

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::turtlebot_2dnav::returnCostResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtlebot_2dnav::returnCostResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtlebot_2dnav::returnCostResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtlebot_2dnav::returnCostResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtlebot_2dnav::returnCostResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtlebot_2dnav::returnCostResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::turtlebot_2dnav::returnCostResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b6afcd538e7323896023cc11da5d0344";
  }

  static const char* value(const ::turtlebot_2dnav::returnCostResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb6afcd538e732389ULL;
  static const uint64_t static_value2 = 0x6023cc11da5d0344ULL;
};

template<class ContainerAllocator>
struct DataType< ::turtlebot_2dnav::returnCostResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "turtlebot_2dnav/returnCostResponse";
  }

  static const char* value(const ::turtlebot_2dnav::returnCostResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::turtlebot_2dnav::returnCostResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"int64 cost\n"
"\n"
;
  }

  static const char* value(const ::turtlebot_2dnav::returnCostResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::turtlebot_2dnav::returnCostResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.cost);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct returnCostResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::turtlebot_2dnav::returnCostResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::turtlebot_2dnav::returnCostResponse_<ContainerAllocator>& v)
  {
    s << indent << "cost: ";
    Printer<int64_t>::stream(s, indent + "  ", v.cost);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TURTLEBOT_2DNAV_MESSAGE_RETURNCOSTRESPONSE_H
