// Auto-generated. Do not edit!

// (in-package explore_lite.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class greedyGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.greedy = null;
    }
    else {
      if (initObj.hasOwnProperty('greedy')) {
        this.greedy = initObj.greedy
      }
      else {
        this.greedy = false;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type greedyGoal
    // Serialize message field [greedy]
    bufferOffset = _serializer.bool(obj.greedy, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type greedyGoal
    let len;
    let data = new greedyGoal(null);
    // Deserialize message field [greedy]
    data.greedy = _deserializer.bool(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 1;
  }

  static datatype() {
    // Returns string type for a message object
    return 'explore_lite/greedyGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '761b58045690b0080d530d2d9fe65b5c';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    bool greedy
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new greedyGoal(null);
    if (msg.greedy !== undefined) {
      resolved.greedy = msg.greedy;
    }
    else {
      resolved.greedy = false
    }

    return resolved;
    }
};

module.exports = greedyGoal;
