(cl:defpackage explore_lite-msg
  (:use )
  (:export
   "<GREEDYACTION>"
   "GREEDYACTION"
   "<GREEDYACTIONFEEDBACK>"
   "GREEDYACTIONFEEDBACK"
   "<GREEDYACTIONGOAL>"
   "GREEDYACTIONGOAL"
   "<GREEDYACTIONRESULT>"
   "GREEDYACTIONRESULT"
   "<GREEDYFEEDBACK>"
   "GREEDYFEEDBACK"
   "<GREEDYGOAL>"
   "GREEDYGOAL"
   "<GREEDYRESULT>"
   "GREEDYRESULT"
  ))

