; Auto-generated. Do not edit!


(cl:in-package explore_lite-msg)


;//! \htmlinclude greedyGoal.msg.html

(cl:defclass <greedyGoal> (roslisp-msg-protocol:ros-message)
  ((greedy
    :reader greedy
    :initarg :greedy
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass greedyGoal (<greedyGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <greedyGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'greedyGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name explore_lite-msg:<greedyGoal> is deprecated: use explore_lite-msg:greedyGoal instead.")))

(cl:ensure-generic-function 'greedy-val :lambda-list '(m))
(cl:defmethod greedy-val ((m <greedyGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader explore_lite-msg:greedy-val is deprecated.  Use explore_lite-msg:greedy instead.")
  (greedy m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <greedyGoal>) ostream)
  "Serializes a message object of type '<greedyGoal>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'greedy) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <greedyGoal>) istream)
  "Deserializes a message object of type '<greedyGoal>"
    (cl:setf (cl:slot-value msg 'greedy) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<greedyGoal>)))
  "Returns string type for a message object of type '<greedyGoal>"
  "explore_lite/greedyGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'greedyGoal)))
  "Returns string type for a message object of type 'greedyGoal"
  "explore_lite/greedyGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<greedyGoal>)))
  "Returns md5sum for a message object of type '<greedyGoal>"
  "761b58045690b0080d530d2d9fe65b5c")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'greedyGoal)))
  "Returns md5sum for a message object of type 'greedyGoal"
  "761b58045690b0080d530d2d9fe65b5c")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<greedyGoal>)))
  "Returns full string definition for message of type '<greedyGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%bool greedy~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'greedyGoal)))
  "Returns full string definition for message of type 'greedyGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%bool greedy~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <greedyGoal>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <greedyGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'greedyGoal
    (cl:cons ':greedy (greedy msg))
))
