; Auto-generated. Do not edit!


(cl:in-package explore_lite-msg)


;//! \htmlinclude greedyFeedback.msg.html

(cl:defclass <greedyFeedback> (roslisp-msg-protocol:ros-message)
  ((received
    :reader received
    :initarg :received
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass greedyFeedback (<greedyFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <greedyFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'greedyFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name explore_lite-msg:<greedyFeedback> is deprecated: use explore_lite-msg:greedyFeedback instead.")))

(cl:ensure-generic-function 'received-val :lambda-list '(m))
(cl:defmethod received-val ((m <greedyFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader explore_lite-msg:received-val is deprecated.  Use explore_lite-msg:received instead.")
  (received m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <greedyFeedback>) ostream)
  "Serializes a message object of type '<greedyFeedback>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'received) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <greedyFeedback>) istream)
  "Deserializes a message object of type '<greedyFeedback>"
    (cl:setf (cl:slot-value msg 'received) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<greedyFeedback>)))
  "Returns string type for a message object of type '<greedyFeedback>"
  "explore_lite/greedyFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'greedyFeedback)))
  "Returns string type for a message object of type 'greedyFeedback"
  "explore_lite/greedyFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<greedyFeedback>)))
  "Returns md5sum for a message object of type '<greedyFeedback>"
  "dd4152e077925db952c78baadb1e48b7")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'greedyFeedback)))
  "Returns md5sum for a message object of type 'greedyFeedback"
  "dd4152e077925db952c78baadb1e48b7")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<greedyFeedback>)))
  "Returns full string definition for message of type '<greedyFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%bool received~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'greedyFeedback)))
  "Returns full string definition for message of type 'greedyFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%bool received~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <greedyFeedback>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <greedyFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'greedyFeedback
    (cl:cons ':received (received msg))
))
