; Auto-generated. Do not edit!


(cl:in-package explore_lite-msg)


;//! \htmlinclude greedyResult.msg.html

(cl:defclass <greedyResult> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass greedyResult (<greedyResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <greedyResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'greedyResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name explore_lite-msg:<greedyResult> is deprecated: use explore_lite-msg:greedyResult instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <greedyResult>) ostream)
  "Serializes a message object of type '<greedyResult>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <greedyResult>) istream)
  "Deserializes a message object of type '<greedyResult>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<greedyResult>)))
  "Returns string type for a message object of type '<greedyResult>"
  "explore_lite/greedyResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'greedyResult)))
  "Returns string type for a message object of type 'greedyResult"
  "explore_lite/greedyResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<greedyResult>)))
  "Returns md5sum for a message object of type '<greedyResult>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'greedyResult)))
  "Returns md5sum for a message object of type 'greedyResult"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<greedyResult>)))
  "Returns full string definition for message of type '<greedyResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'greedyResult)))
  "Returns full string definition for message of type 'greedyResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <greedyResult>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <greedyResult>))
  "Converts a ROS message object to a list"
  (cl:list 'greedyResult
))
