# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from turtlebot_2dnav/CarryingPersonRequest.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import turtlebot_2dnav.msg
import std_msgs.msg

class CarryingPersonRequest(genpy.Message):
  _md5sum = "60b1f66dc52c1ec4715013a78543dbbd"
  _type = "turtlebot_2dnav/CarryingPersonRequest"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """turtlebot_2dnav/ROI person


================================================================================
MSG: turtlebot_2dnav/ROI
Header Header
string type
geometry_msgs/Point center
float32 size_x
float32 size_y
uint8 index
bool isnew

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z
"""
  __slots__ = ['person']
  _slot_types = ['turtlebot_2dnav/ROI']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       person

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(CarryingPersonRequest, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.person is None:
        self.person = turtlebot_2dnav.msg.ROI()
    else:
      self.person = turtlebot_2dnav.msg.ROI()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.person.Header.seq, _x.person.Header.stamp.secs, _x.person.Header.stamp.nsecs))
      _x = self.person.Header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.person.type
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_3d2f2B().pack(_x.person.center.x, _x.person.center.y, _x.person.center.z, _x.person.size_x, _x.person.size_y, _x.person.index, _x.person.isnew))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.person is None:
        self.person = turtlebot_2dnav.msg.ROI()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.person.Header.seq, _x.person.Header.stamp.secs, _x.person.Header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.person.Header.frame_id = str[start:end].decode('utf-8')
      else:
        self.person.Header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.person.type = str[start:end].decode('utf-8')
      else:
        self.person.type = str[start:end]
      _x = self
      start = end
      end += 34
      (_x.person.center.x, _x.person.center.y, _x.person.center.z, _x.person.size_x, _x.person.size_y, _x.person.index, _x.person.isnew,) = _get_struct_3d2f2B().unpack(str[start:end])
      self.person.isnew = bool(self.person.isnew)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.person.Header.seq, _x.person.Header.stamp.secs, _x.person.Header.stamp.nsecs))
      _x = self.person.Header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.person.type
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_3d2f2B().pack(_x.person.center.x, _x.person.center.y, _x.person.center.z, _x.person.size_x, _x.person.size_y, _x.person.index, _x.person.isnew))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.person is None:
        self.person = turtlebot_2dnav.msg.ROI()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.person.Header.seq, _x.person.Header.stamp.secs, _x.person.Header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.person.Header.frame_id = str[start:end].decode('utf-8')
      else:
        self.person.Header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.person.type = str[start:end].decode('utf-8')
      else:
        self.person.type = str[start:end]
      _x = self
      start = end
      end += 34
      (_x.person.center.x, _x.person.center.y, _x.person.center.z, _x.person.size_x, _x.person.size_y, _x.person.index, _x.person.isnew,) = _get_struct_3d2f2B().unpack(str[start:end])
      self.person.isnew = bool(self.person.isnew)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_3d2f2B = None
def _get_struct_3d2f2B():
    global _struct_3d2f2B
    if _struct_3d2f2B is None:
        _struct_3d2f2B = struct.Struct("<3d2f2B")
    return _struct_3d2f2B
# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from turtlebot_2dnav/CarryingPersonResponse.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class CarryingPersonResponse(genpy.Message):
  _md5sum = "dd4152e077925db952c78baadb1e48b7"
  _type = "turtlebot_2dnav/CarryingPersonResponse"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """
bool received

"""
  __slots__ = ['received']
  _slot_types = ['bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       received

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(CarryingPersonResponse, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.received is None:
        self.received = False
    else:
      self.received = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      buff.write(_get_struct_B().pack(self.received))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      start = end
      end += 1
      (self.received,) = _get_struct_B().unpack(str[start:end])
      self.received = bool(self.received)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      buff.write(_get_struct_B().pack(self.received))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      start = end
      end += 1
      (self.received,) = _get_struct_B().unpack(str[start:end])
      self.received = bool(self.received)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_B = None
def _get_struct_B():
    global _struct_B
    if _struct_B is None:
        _struct_B = struct.Struct("<B")
    return _struct_B
class CarryingPerson(object):
  _type          = 'turtlebot_2dnav/CarryingPerson'
  _md5sum = '483ed3a7747788a7b78a207bdc605ba1'
  _request_class  = CarryingPersonRequest
  _response_class = CarryingPersonResponse
