# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from turtlebot_2dnav/match_bound.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class match_bound(genpy.Message):
  _md5sum = "c25fb2723cbd0da8861846f432114884"
  _type = "turtlebot_2dnav/match_bound"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """geometry_msgs/Point pointright
geometry_msgs/Point pointleft
geometry_msgs/Point pointcenter
bool matched
int32 index
int32 color

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z
"""
  __slots__ = ['pointright','pointleft','pointcenter','matched','index','color']
  _slot_types = ['geometry_msgs/Point','geometry_msgs/Point','geometry_msgs/Point','bool','int32','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       pointright,pointleft,pointcenter,matched,index,color

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(match_bound, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.pointright is None:
        self.pointright = geometry_msgs.msg.Point()
      if self.pointleft is None:
        self.pointleft = geometry_msgs.msg.Point()
      if self.pointcenter is None:
        self.pointcenter = geometry_msgs.msg.Point()
      if self.matched is None:
        self.matched = False
      if self.index is None:
        self.index = 0
      if self.color is None:
        self.color = 0
    else:
      self.pointright = geometry_msgs.msg.Point()
      self.pointleft = geometry_msgs.msg.Point()
      self.pointcenter = geometry_msgs.msg.Point()
      self.matched = False
      self.index = 0
      self.color = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_9dB2i().pack(_x.pointright.x, _x.pointright.y, _x.pointright.z, _x.pointleft.x, _x.pointleft.y, _x.pointleft.z, _x.pointcenter.x, _x.pointcenter.y, _x.pointcenter.z, _x.matched, _x.index, _x.color))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.pointright is None:
        self.pointright = geometry_msgs.msg.Point()
      if self.pointleft is None:
        self.pointleft = geometry_msgs.msg.Point()
      if self.pointcenter is None:
        self.pointcenter = geometry_msgs.msg.Point()
      end = 0
      _x = self
      start = end
      end += 81
      (_x.pointright.x, _x.pointright.y, _x.pointright.z, _x.pointleft.x, _x.pointleft.y, _x.pointleft.z, _x.pointcenter.x, _x.pointcenter.y, _x.pointcenter.z, _x.matched, _x.index, _x.color,) = _get_struct_9dB2i().unpack(str[start:end])
      self.matched = bool(self.matched)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_9dB2i().pack(_x.pointright.x, _x.pointright.y, _x.pointright.z, _x.pointleft.x, _x.pointleft.y, _x.pointleft.z, _x.pointcenter.x, _x.pointcenter.y, _x.pointcenter.z, _x.matched, _x.index, _x.color))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.pointright is None:
        self.pointright = geometry_msgs.msg.Point()
      if self.pointleft is None:
        self.pointleft = geometry_msgs.msg.Point()
      if self.pointcenter is None:
        self.pointcenter = geometry_msgs.msg.Point()
      end = 0
      _x = self
      start = end
      end += 81
      (_x.pointright.x, _x.pointright.y, _x.pointright.z, _x.pointleft.x, _x.pointleft.y, _x.pointleft.z, _x.pointcenter.x, _x.pointcenter.y, _x.pointcenter.z, _x.matched, _x.index, _x.color,) = _get_struct_9dB2i().unpack(str[start:end])
      self.matched = bool(self.matched)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_9dB2i = None
def _get_struct_9dB2i():
    global _struct_9dB2i
    if _struct_9dB2i is None:
        _struct_9dB2i = struct.Struct("<9dB2i")
    return _struct_9dB2i
