// Generated by gencpp from file explore_lite/greedyResult.msg
// DO NOT EDIT!


#ifndef EXPLORE_LITE_MESSAGE_GREEDYRESULT_H
#define EXPLORE_LITE_MESSAGE_GREEDYRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace explore_lite
{
template <class ContainerAllocator>
struct greedyResult_
{
  typedef greedyResult_<ContainerAllocator> Type;

  greedyResult_()
    {
    }
  greedyResult_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::explore_lite::greedyResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::explore_lite::greedyResult_<ContainerAllocator> const> ConstPtr;

}; // struct greedyResult_

typedef ::explore_lite::greedyResult_<std::allocator<void> > greedyResult;

typedef boost::shared_ptr< ::explore_lite::greedyResult > greedyResultPtr;
typedef boost::shared_ptr< ::explore_lite::greedyResult const> greedyResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::explore_lite::greedyResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::explore_lite::greedyResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace explore_lite

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::explore_lite::greedyResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::explore_lite::greedyResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::explore_lite::greedyResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::explore_lite::greedyResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::explore_lite::greedyResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::explore_lite::greedyResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::explore_lite::greedyResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::explore_lite::greedyResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::explore_lite::greedyResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "explore_lite/greedyResult";
  }

  static const char* value(const ::explore_lite::greedyResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::explore_lite::greedyResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
;
  }

  static const char* value(const ::explore_lite::greedyResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::explore_lite::greedyResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct greedyResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::explore_lite::greedyResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::explore_lite::greedyResult_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // EXPLORE_LITE_MESSAGE_GREEDYRESULT_H
