// Generated by gencpp from file explore_lite/greedyGoal.msg
// DO NOT EDIT!


#ifndef EXPLORE_LITE_MESSAGE_GREEDYGOAL_H
#define EXPLORE_LITE_MESSAGE_GREEDYGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace explore_lite
{
template <class ContainerAllocator>
struct greedyGoal_
{
  typedef greedyGoal_<ContainerAllocator> Type;

  greedyGoal_()
    : greedy(false)  {
    }
  greedyGoal_(const ContainerAllocator& _alloc)
    : greedy(false)  {
  (void)_alloc;
    }



   typedef uint8_t _greedy_type;
  _greedy_type greedy;





  typedef boost::shared_ptr< ::explore_lite::greedyGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::explore_lite::greedyGoal_<ContainerAllocator> const> ConstPtr;

}; // struct greedyGoal_

typedef ::explore_lite::greedyGoal_<std::allocator<void> > greedyGoal;

typedef boost::shared_ptr< ::explore_lite::greedyGoal > greedyGoalPtr;
typedef boost::shared_ptr< ::explore_lite::greedyGoal const> greedyGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::explore_lite::greedyGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::explore_lite::greedyGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::explore_lite::greedyGoal_<ContainerAllocator1> & lhs, const ::explore_lite::greedyGoal_<ContainerAllocator2> & rhs)
{
  return lhs.greedy == rhs.greedy;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::explore_lite::greedyGoal_<ContainerAllocator1> & lhs, const ::explore_lite::greedyGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace explore_lite

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::explore_lite::greedyGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::explore_lite::greedyGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::explore_lite::greedyGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::explore_lite::greedyGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::explore_lite::greedyGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::explore_lite::greedyGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::explore_lite::greedyGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "761b58045690b0080d530d2d9fe65b5c";
  }

  static const char* value(const ::explore_lite::greedyGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x761b58045690b008ULL;
  static const uint64_t static_value2 = 0x0d530d2d9fe65b5cULL;
};

template<class ContainerAllocator>
struct DataType< ::explore_lite::greedyGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "explore_lite/greedyGoal";
  }

  static const char* value(const ::explore_lite::greedyGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::explore_lite::greedyGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"bool greedy\n"
;
  }

  static const char* value(const ::explore_lite::greedyGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::explore_lite::greedyGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.greedy);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct greedyGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::explore_lite::greedyGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::explore_lite::greedyGoal_<ContainerAllocator>& v)
  {
    s << indent << "greedy: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.greedy);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EXPLORE_LITE_MESSAGE_GREEDYGOAL_H
