// Generated by gencpp from file explore_lite/greedyFeedback.msg
// DO NOT EDIT!


#ifndef EXPLORE_LITE_MESSAGE_GREEDYFEEDBACK_H
#define EXPLORE_LITE_MESSAGE_GREEDYFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace explore_lite
{
template <class ContainerAllocator>
struct greedyFeedback_
{
  typedef greedyFeedback_<ContainerAllocator> Type;

  greedyFeedback_()
    : received(false)  {
    }
  greedyFeedback_(const ContainerAllocator& _alloc)
    : received(false)  {
  (void)_alloc;
    }



   typedef uint8_t _received_type;
  _received_type received;





  typedef boost::shared_ptr< ::explore_lite::greedyFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::explore_lite::greedyFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct greedyFeedback_

typedef ::explore_lite::greedyFeedback_<std::allocator<void> > greedyFeedback;

typedef boost::shared_ptr< ::explore_lite::greedyFeedback > greedyFeedbackPtr;
typedef boost::shared_ptr< ::explore_lite::greedyFeedback const> greedyFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::explore_lite::greedyFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::explore_lite::greedyFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::explore_lite::greedyFeedback_<ContainerAllocator1> & lhs, const ::explore_lite::greedyFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.received == rhs.received;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::explore_lite::greedyFeedback_<ContainerAllocator1> & lhs, const ::explore_lite::greedyFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace explore_lite

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::explore_lite::greedyFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::explore_lite::greedyFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::explore_lite::greedyFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::explore_lite::greedyFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::explore_lite::greedyFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::explore_lite::greedyFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::explore_lite::greedyFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dd4152e077925db952c78baadb1e48b7";
  }

  static const char* value(const ::explore_lite::greedyFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdd4152e077925db9ULL;
  static const uint64_t static_value2 = 0x52c78baadb1e48b7ULL;
};

template<class ContainerAllocator>
struct DataType< ::explore_lite::greedyFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "explore_lite/greedyFeedback";
  }

  static const char* value(const ::explore_lite::greedyFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::explore_lite::greedyFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"bool received\n"
"\n"
;
  }

  static const char* value(const ::explore_lite::greedyFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::explore_lite::greedyFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.received);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct greedyFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::explore_lite::greedyFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::explore_lite::greedyFeedback_<ContainerAllocator>& v)
  {
    s << indent << "received: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.received);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EXPLORE_LITE_MESSAGE_GREEDYFEEDBACK_H
